services:

  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: media_pgl_app

    ports:
      - "8000:8000"

    env_file:
      - .env.docker

    depends_on:
      db:
        condition: service_healthy

    restart: unless-stopped


  db:
    image: mysql:8.0

    container_name: media_pgl_db

    environment:
      MYSQL_DATABASE: db_mediapgl
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel123
      MYSQL_ROOT_PASSWORD: root123

    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -uroot -p$$MYSQL_ROOT_PASSWORD --silent"
        ]

      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s

    restart: unless-stopped


volumes:
  db_data:
